apiVersion: v2
name: zeus
description: Tests ArgoCD
type: application
version: 1.0.0
appVersion: "1.0.0"
dependencies:
  - name: nats
    version: "1.2.1"
    repository: https://nats-io.github.io/k8s/helm/charts/

  - name: jaeger
    version: "3.1.1"
    repository: https://jaegertracing.github.io/helm-charts
