apiVersion: v2
name: zeus
description: Tests ArgoCD
type: application
version: 1.0.0
appVersion: "1.0.0"
dependencies:
  - name: kubernetes-dashboard
    version: "7.10.5"
    repository: https://kubernetes.github.io/dashboard/
    alias: dashboard

  - name: metrics-server
    version: 3.12.2
    repository: https://kubernetes-sigs.github.io/metrics-server
    alias: metrics-server

  - name: kube-prometheus-stack
    version: "70.0.2"
    repository: https://prometheus-community.github.io/helm-charts
    alias: prometheus
    condition: prometheus.enabled

  - name: redis
    repository: https://charts.bitnami.com/bitnami
    version: 19.6.2
    alias: redis

  - name: nats
    version: "1.2.1"
    repository: https://nats-io.github.io/k8s/helm/charts/

  - name: jaeger
    version: "3.1.1"
    repository: https://jaegertracing.github.io/helm-charts

  - name: postgresql
    version: "12.5.6"
    repository: https://charts.bitnami.com/bitnami
    alias: postgresqlBD
    condition: postgresqlBD.enabled